import '../../features/account/domain/entities/account_user.dart';
import '../../features/colis/domain/entities/colis.dart';
import '../../features/notifications/domain/entities/notification_app.dart';
import '../../features/paiements/domain/entities/facture_colis.dart';
import '../../features/villes/domain/entities/ville.dart';

/// Données fictives mais réalistes pour le mode démo (voir demo_config.dart).
/// Centralisées ici pour être faciles à retirer une fois le backend branché.
class DemoData {
  DemoData._();

  static final villes = <Ville>[
    const Ville(id: 'v-dakar', nom: 'Dakar', region: 'Dakar'),
    const Ville(id: 'v-thies', nom: 'Thiès', region: 'Thiès'),
    const Ville(id: 'v-saint-louis', nom: 'Saint-Louis', region: 'Saint-Louis'),
    const Ville(id: 'v-kaolack', nom: 'Kaolack', region: 'Kaolack'),
    const Ville(id: 'v-ziguinchor', nom: 'Ziguinchor', region: 'Ziguinchor'),
    const Ville(id: 'v-touba', nom: 'Touba', region: 'Diourbel'),
    const Ville(id: 'v-mbour', nom: 'Mbour', region: 'Thiès'),
  ];

  static AccountUser account = const AccountUser(
    id: 'demo-user-1',
    nom: 'Diallo',
    prenom: 'Fatou',
    email: 'fatou.diallo@yobante.sn',
    telephone: '77 123 45 67',
    role: 'client',
    avatarUrl: null,
    isActive: true,
  );

  static final List<Colis> colis = [
    Colis(
      id: 'demo-colis-1',
      reference: 'YBC-2026-0128',
      service: const ServiceRef(id: 's-standard', code: 'STD', nom: 'Standard'),
      expediteurNom: 'Fatou Diallo',
      expediteurTelephone: '77 123 45 67',
      paysDepart: 'SN',
      villeDepartId: 'v-dakar',
      villeDepart: const VilleRef(id: 'v-dakar', nom: 'Dakar', pays: 'SN'),
      destinataireNom: 'Aminata Fall',
      destinataireTelephone: '76 540 12 98',
      paysArrivee: 'SN',
      villeArriveeId: 'v-thies',
      villeArrivee: const VilleRef(id: 'v-thies', nom: 'Thiès', pays: 'SN'),
      adresseLivraison: 'Cité Malick Sy, Villa 24, Thiès',
      description: 'Vêtements et accessoires',
      typeContenu: 'marchandise',
      poidsFactureKg: 2.5,
      valeurDeclaree: 25000,
      montantTotal: 3500,
      statut: 'livre',
      photos: const [],
      dateLivraisonEstimee: DateTime.now().subtract(const Duration(days: 8)).toIso8601String(),
      dateLivraisonEffective: DateTime.now().subtract(const Duration(days: 8)).toIso8601String(),
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    Colis(
      id: 'demo-colis-2',
      reference: 'YBC-2026-0134',
      service: const ServiceRef(id: 's-express', code: 'EXP', nom: 'Express'),
      expediteurNom: 'Fatou Diallo',
      expediteurTelephone: '77 123 45 67',
      paysDepart: 'SN',
      villeDepartId: 'v-dakar',
      villeDepart: const VilleRef(id: 'v-dakar', nom: 'Dakar', pays: 'SN'),
      destinataireNom: 'Ibrahima Ndiaye',
      destinataireTelephone: '70 233 44 12',
      paysArrivee: 'SN',
      villeArriveeId: 'v-saint-louis',
      villeArrivee: const VilleRef(id: 'v-saint-louis', nom: 'Saint-Louis', pays: 'SN'),
      adresseLivraison: 'Quartier Sor, Saint-Louis',
      description: 'Documents administratifs',
      typeContenu: 'document',
      poidsFactureKg: 1.0,
      montantTotal: 6000,
      statut: 'en_transit',
      photos: const [],
      dateLivraisonEstimee: DateTime.now().add(const Duration(days: 1)).toIso8601String(),
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Colis(
      id: 'demo-colis-3',
      reference: 'YBC-2026-0141',
      service: const ServiceRef(id: 's-standard', code: 'STD', nom: 'Standard'),
      expediteurNom: 'Fatou Diallo',
      expediteurTelephone: '77 123 45 67',
      paysDepart: 'SN',
      villeDepartId: 'v-dakar',
      villeDepart: const VilleRef(id: 'v-dakar', nom: 'Dakar', pays: 'SN'),
      destinataireNom: 'Astou Gueye',
      destinataireTelephone: '78 902 61 45',
      paysArrivee: 'SN',
      villeArriveeId: 'v-mbour',
      villeArrivee: const VilleRef(id: 'v-mbour', nom: 'Mbour', pays: 'SN'),
      adresseLivraison: 'Marché Sandika, Mbour',
      description: 'Matériel électronique — fragile',
      typeContenu: 'marchandise',
      fragile: true,
      poidsFactureKg: 4.2,
      valeurDeclaree: 85000,
      montantTotal: 5000,
      statut: 'en_preparation',
      photos: const [],
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    Colis(
      id: 'demo-colis-4',
      reference: 'YBC-2026-0145',
      service: const ServiceRef(id: 's-standard', code: 'STD', nom: 'Standard'),
      expediteurNom: 'Fatou Diallo',
      expediteurTelephone: '77 123 45 67',
      paysDepart: 'SN',
      villeDepartId: 'v-dakar',
      villeDepart: const VilleRef(id: 'v-dakar', nom: 'Dakar', pays: 'SN'),
      destinataireNom: 'Mariama Sy',
      destinataireTelephone: '77 654 32 10',
      paysArrivee: 'SN',
      villeArriveeId: 'v-touba',
      villeArrivee: const VilleRef(id: 'v-touba', nom: 'Touba', pays: 'SN'),
      adresseLivraison: 'Quartier Darou Marnane, Touba',
      typeContenu: 'marchandise',
      poidsFactureKg: 3.0,
      montantTotal: 4000,
      statut: 'en_attente',
      photos: const [],
      createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
    ),
    Colis(
      id: 'demo-colis-5',
      reference: 'YBC-2026-0109',
      service: const ServiceRef(id: 's-standard', code: 'STD', nom: 'Standard'),
      expediteurNom: 'Fatou Diallo',
      expediteurTelephone: '77 123 45 67',
      paysDepart: 'SN',
      villeDepartId: 'v-dakar',
      villeDepart: const VilleRef(id: 'v-dakar', nom: 'Dakar', pays: 'SN'),
      destinataireNom: 'Cheikh Ba',
      destinataireTelephone: '76 111 22 33',
      paysArrivee: 'SN',
      villeArriveeId: 'v-kaolack',
      villeArrivee: const VilleRef(id: 'v-kaolack', nom: 'Kaolack', pays: 'SN'),
      adresseLivraison: 'Route de Ndoffane, Kaolack',
      typeContenu: 'marchandise',
      poidsFactureKg: 1.8,
      montantTotal: 3000,
      statut: 'annule',
      annuleMotif: 'Destinataire injoignable',
      photos: const [],
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
    ),
  ];

  static final List<FactureColis> factures = [
    FactureColis(
      id: 'demo-facture-1',
      reference: 'FAC-2026-0128',
      colisId: 'demo-colis-1',
      montantTransport: 3500,
      remise: 0,
      montantTotal: 3500,
      statut: 'payee',
      dateEmission: DateTime.now().subtract(const Duration(days: 10)).toIso8601String(),
    ),
    FactureColis(
      id: 'demo-facture-2',
      reference: 'FAC-2026-0134',
      colisId: 'demo-colis-2',
      montantTransport: 6500,
      remise: 500,
      montantTotal: 6000,
      statut: 'payee',
      dateEmission: DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    ),
    FactureColis(
      id: 'demo-facture-3',
      reference: 'FAC-2026-0141',
      colisId: 'demo-colis-3',
      montantTransport: 5000,
      remise: 0,
      montantTotal: 5000,
      statut: 'en_attente',
      dateEmission: DateTime.now().subtract(const Duration(hours: 6)).toIso8601String(),
    ),
    FactureColis(
      id: 'demo-facture-4',
      reference: 'FAC-2026-0109',
      colisId: 'demo-colis-5',
      montantTransport: 3000,
      remise: 0,
      montantTotal: 3000,
      statut: 'annulee',
      dateEmission: DateTime.now().subtract(const Duration(days: 15)).toIso8601String(),
    ),
  ];

  static final List<NotificationApp> notifications = [
    NotificationApp(
      id: 'demo-notif-1',
      titre: 'Colis en transit',
      message: 'Votre colis YBC-2026-0134 est en route vers Saint-Louis.',
      type: 'colis',
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    NotificationApp(
      id: 'demo-notif-2',
      titre: 'Paiement confirmé',
      message: 'La facture FAC-2026-0134 a été payée avec succès.',
      type: 'paiement',
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    NotificationApp(
      id: 'demo-notif-3',
      titre: 'Colis livré',
      message: 'Votre colis YBC-2026-0128 a bien été livré à Aminata Fall.',
      type: 'colis',
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
    ),
    NotificationApp(
      id: 'demo-notif-4',
      titre: 'Bienvenue sur Yobante Colis',
      message: 'Créez votre premier envoi en quelques secondes.',
      type: 'compte',
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
  ];
}
